<a href="https://colab.research.google.com/github/yrhutu21/Computer_Vision/blob/main/MNIST_Digit_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import torch
from torchvision import datasets, transforms

In [48]:
dataset = datasets.MNIST(root='./data', train=True, download=True,
                         transform=transforms.ToTensor())

In [49]:
x_train = dataset.data
y_train = dataset.targets

In [50]:
selected_classes = [0, 1, 2]

In [51]:
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    print(indices)

tensor([   1,   21,   34,   37,   51,   56,   63,   68,   69,   75,   81,   88,
          95,  108,  114,  118,  119,  121,  156,  169,  192,  206,  209,  210,
         216,  229,  232,  234,  246,  249,  260,  283,  293,  296,  303,  320,
         326,  359,  399,  427,  429,  435,  440,  451,  453,  458,  462,  464,
         473,  489,  519,  524,  526,  527,  542,  577,  582,  596,  603,  612,
         633,  639,  656,  662,  666,  667,  668,  669,  689,  702,  709,  712,
         733,  743,  745,  776,  781,  787,  790,  818,  825,  849,  859,  860,
         869,  872,  889,  903,  927,  943,  949,  952,  957,  965,  979,  984,
         997, 1000, 1015, 1018])
tensor([  3,   6,   8,  14,  23,  24,  40,  59,  67,  70,  72,  77,  78,  99,
        102, 104, 105, 112, 113, 124, 128, 134, 152, 174, 177, 184, 200, 201,
        205, 208, 211, 224, 231, 248, 251, 269, 270, 276, 290, 309, 310, 315,
        345, 351, 355, 357, 358, 366, 382, 394, 397, 398, 406, 408, 416, 443,
        447, 45

In [52]:
x_final, y_final = [], []
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    x_final.append(x_train[indices])
    y_final.append(y_train[indices])

In [53]:
len(x_final)

3

In [54]:
xx = torch.cat(x_final)
yy = torch.cat(y_final)

In [55]:
yy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [56]:
from torch.utils.data import TensorDataset, DataLoader

In [57]:
dataset = TensorDataset(xx, yy)

In [58]:
data = DataLoader(dataset, batch_size=32, shuffle=True)

In [59]:
for batch in data:
    print(batch[0].shape)
    break

torch.Size([32, 28, 28])


In [60]:
for batch in data:
  batch_x = batch[0]
  batch_y = batch[1]
  print(batch_x.shape, batch_y.shape)

torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([12, 28, 28]) torch.Size([12])


In [61]:
#torch.save(model.state_dict(), 'model_weights.pth')

In [62]:
#model = ModelArchitecture()
#model.load_state_dict(torch.load('model_weights.pth'))
#model.eval()

Training

In [63]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [64]:
transform = transforms.ToTensor()

train_data = datasets.MNIST('./data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

In [65]:
model = nn.Sequential(
    nn.Conv2d(1, 8, kernel_size=3),
    nn.ReLU(),
    nn.MaxPool2d(2),

    nn.Flatten(),

    nn.Linear(8 * 13 * 13, 128),
    nn.ReLU(),
    nn.Linear(128, 10)
)

In [66]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [67]:
for epoch in range(5):
    for X, Y in train_loader:

        optimizer.zero_grad()      # clear gradients

        output = model(X)          # forward
        loss = loss_fn(output, Y)  # loss

        loss.backward()            # backprop
        optimizer.step()           # update weights

    print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 0.06632702797651291
Epoch: 1 Loss: 0.030643021687865257
Epoch: 2 Loss: 0.015343278646469116
Epoch: 3 Loss: 0.005825831089168787
Epoch: 4 Loss: 0.0013352958485484123


Training Using Class Based model

In [68]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [69]:
transform = transforms.ToTensor()

train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_data = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32)

In [70]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Conv2d(1, 8, kernel_size=3)   # (1 → 8 channels)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2)

        self.fc1 = nn.Linear(8 * 13 * 13, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(self.relu(self.conv(x)))
        x = x.view(x.size(0), -1)   # flatten
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [71]:
model = MyModel()

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [72]:
for epoch in range(5):
    for X, Y in train_loader:

        optimizer.zero_grad()       # clear old gradients

        output = model(X)           # forward pass
        loss = loss_fn(output, Y)   # calculate loss

        loss.backward()             # backpropagation
        optimizer.step()            # update weights

    print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 0.20208045840263367
Epoch: 1 Loss: 0.29296666383743286
Epoch: 2 Loss: 0.004015293437987566
Epoch: 3 Loss: 0.015373905189335346
Epoch: 4 Loss: 0.010425028391182423


Testing using Class Based Model

In [73]:
correct = 0
total = 0

with torch.no_grad():
    for X, Y in test_loader:
        output = model(X)
        _, predicted = torch.max(output, 1)

        total += Y.size(0)
        correct += (predicted == Y).sum().item()

print("Accuracy:", correct / total)

Accuracy: 0.9817


In [74]:
with torch.no_grad():
    for X, Y in test_loader:
        output = model(X)
        _, predicted = torch.max(output, 1)

        for i in range(10):
            print(f"Actual: {Y[i].item()}  |  Predicted: {predicted[i].item()}")
        break

Actual: 7  |  Predicted: 7
Actual: 2  |  Predicted: 2
Actual: 1  |  Predicted: 1
Actual: 0  |  Predicted: 0
Actual: 4  |  Predicted: 4
Actual: 1  |  Predicted: 1
Actual: 4  |  Predicted: 4
Actual: 9  |  Predicted: 9
Actual: 5  |  Predicted: 5
Actual: 9  |  Predicted: 9


Model Tested using an External Image

In [75]:
#pip install pillow

In [76]:
from PIL import Image
import torchvision.transforms as transforms

# Load image
img = Image.open("zero_num.png").convert("L")  # convert to grayscale

# Define same transform as training
transform = transforms.Compose([
    transforms.Resize((28, 28)),   # MNIST size
    transforms.ToTensor()
])

img = transform(img)

# Add batch dimension → [1, 1, 28, 28]
img = img.unsqueeze(0)

In [77]:
model.eval()   # set model to evaluation mode

with torch.no_grad():
    output = model(img)
    _, predicted = torch.max(output, 1)

print("Predicted Digit:", predicted.item())

Predicted Digit: 0


Model Tested Using CV

In [78]:
import cv2
import torch
import numpy as np

In [79]:
img = cv2.imread("zero.webp", cv2.IMREAD_GRAYSCALE)

In [80]:
img = cv2.resize(img, (28, 28))

In [81]:
img = cv2.bitwise_not(img)

In [82]:
_, img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

In [83]:
img = img / 255.0

In [84]:
img = torch.tensor(img, dtype=torch.float32)

# Add channel and batch → [1, 1, 28, 28]
img = img.unsqueeze(0).unsqueeze(0)

In [85]:
model.eval()

with torch.no_grad():
    output = model(img)
    _, pred = torch.max(output, 1)

print("Predicted Digit:", pred.item())

Predicted Digit: 3
